"""Export the comparison payload for the static page."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

from .sectors import NOTES, SECTORS

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "data" / "artifacts"
SITE = ROOT / "site"
ARTIFACTS.mkdir(parents=True, exist_ok=True)


def _clean(o):
    if isinstance(o, dict):
        return {str(k): _clean(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_clean(v) for v in o]
    if isinstance(o, np.integer):
        return int(o)
    if isinstance(o, (np.floating, float)):
        f = float(o)
        return None if (np.isnan(f) or np.isinf(f)) else round(f, 6)
    if isinstance(o, pd.Timestamp):
        return str(o.date())
    if isinstance(o, np.ndarray):
        return _clean(o.tolist())
    return o


def _monthly(s: pd.Series) -> list[dict]:
    """Month-end sampling — 120 points instead of 2,500 keeps the payload small
    without changing the shape of a ten-year line."""
    if s.empty:
        return []
    m = s.resample("ME").last().dropna()
    return [{"d": str(pd.Timestamp(i).date()), "v": round(float(v), 2)} for i, v in m.items()]


def build_payload(sectors: dict, fx: dict, lineage: list) -> dict:
    out_sectors = {}
    for key, s in sectors.items():
        out_sectors[key] = {
            "label": s["label"],
            "blurb": s["blurb"],
            "note": NOTES.get(key),
            "cn": {
                "index": _monthly(s["cn"]["index"]),
                "index_cagr": _clean(s["cn"]["index_cagr"]),
                "index_years": s["cn"]["index_years"],
                "index_total_return": _clean(s["cn"]["index_total_return"]),
                "companies": _clean(s["cn"]["companies"]),
                "aggregate": _clean(s["cn"]["aggregate"]),
            },
            "us": {
                "index": _monthly(s["us"]["index"]),
                "index_cagr": _clean(s["us"]["index_cagr"]),
                "index_years": s["us"]["index_years"],
                "index_total_return": _clean(s["us"]["index_total_return"]),
                "companies": _clean(s["us"]["companies"]),
                "aggregate": _clean(s["us"]["aggregate"]),
            },
        }

    return {
        "meta": {
            "title": "China vs US — Where Are the Markets Heading",
            "subtitle": "Ten years of sector-by-sector performance across the two markets "
                        "that matter, and the financials underneath it.",
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "fx": _clean(fx),
            "sector_order": list(SECTORS.keys()),
        },
        "sectors": out_sectors,
        "lineage": _clean(lineage),
        "limitations": [
            "Chinese companies here are Hong Kong listings and US ADRs. Mainland A-shares are "
            "geo-blocked from this network, which excludes Cambricon, Hygon, NAURA, AMEC and "
            "iFlytek — several of China's strongest chip and AI names.",
            "Growth is measured as total return on split- and dividend-adjusted prices. It is "
            "what an investor would have earned, not a measure of business size.",
            "Revenue CAGR uses only the 4–5 annual periods free data provides — it is not a "
            "ten-year figure, and each company's window length is shown next to it.",
            "Foreign currency is converted at current spot, including for historical revenue. "
            "A precise job would use each period's average rate.",
            "Roughly half the Chinese basket listed after 2020, so ten-year index returns for "
            "those sectors describe a changing set of companies. Constituent counts and each "
            "company's listing date are shown.",
            "Index construction is equal-weight, so a $4tn company counts the same as a $5bn "
            "one. Aggregate market cap and revenue are shown separately for scale.",
            "Sector membership is a judgement call. Several supply-chain names (Sunny Optical, "
            "BYD Electronic, AAC) legitimately belong to more than one sector and appear twice.",
            "Nothing here is a forecast. Past growth is not a claim about where either market "
            "goes next.",
        ],
    }


def write(payload: dict) -> None:
    data = _clean(payload)
    (ARTIFACTS / "versus.json").write_text(json.dumps(data, indent=2, ensure_ascii=False))
    (SITE / "data.js").write_text(
        "// Generated by versus.export — do not edit by hand.\n"
        "window.VERSUS = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
